logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: aniu
    password: aniu
    listener:
      simple:
        prefetch: 1