server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: 192.168.31.204:8848 #nacos地址
    gateway:
      routes: #网关路由配置
        - id: user-service #路由id，唯一
          uri: lb://userService #路由地址，ld表示负载均衡，后面跟服务名字
          predicates: #路由断言，判断进来的地址是否满足这组路由的转发要求
            - Path=/user/**
          filters:
            - AddRequestHeader=Xxx, From userService
        - id: order-service
          uri: lb://orderService
          predicates:
            - Path=/order/**
          filters:
            - AddRequestHeader=Xxx, From orderService
      default-filters:
        - AddRequestParameter=isEnableDefaultFilter, YES

      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]': # 拦截所有请求
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:5500"
              - "http://127.0.0.1:5500"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
